spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sellcraftdb
    username: sellcraft_admin
    password: secureSell2024!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/liquibase/db.changelog-master.yaml
