server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:5432/sellcraftdb
    username: ${DB_USER:sellcraft_admin}
    password: ${DB_PASSWORD:secureSell2024!}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/liquibase/db.changelog-master.yaml
